[package]
name = "android_main"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
main = { workspace = true }
winit = { workspace = true, features = ["android-game-activity"]}

[target.'cfg(target_os = "android")'.dependencies]
android_logger = "0.14.1"