[package]
name = "main"
version = "0.1.0"
edition = "2024"

[dependencies]
running_context.workspace = true
winit.workspace = true
nalgebra = "0.33.2"
egui_dock = "0.16"
egui_plot = "0.31"
egui = { workspace = true, features = ["color-hex"] }