[package]
name = "main"
version = "0.1.0"
edition = "2024"

[dependencies]
running_context.workspace = true
winit.workspace = true

egui_dock = {git = "https://github.com/bryceberger/egui_dock.git", branch = "egui-0.30"}
epaint = "0.30.0"
egui = { version = "0.30", features = ["color-hex"] }